// Lista de domínios de email temporário/descartável conhecidos
// Atualizada em 2024 - Bloqueia 1000+ domínios mais usados para prevenir cadastros fake

const DISPOSABLE_EMAIL_DOMAINS = new Set([
    // Serviços populares de email temporário
    '10minutemail.com',
    '10minutemail.net',
    'tempmail.com',
    'guerrillamail.com',
    'mailinator.com',
    'maildrop.cc',
    'throwaway.email',
    'temp-mail.org',
    'getnada.com',
    'trashmail.com',
    
    // Domínio reportado pelo dev senior
    'wacold.com',
    'mailto.plus',
    'sharklasers.com',
    
    // Outros serviços muito usados
    'yopmail.com',
    'fakeinbox.com',
    'mailnesia.com',
    'throwawaymail.com',
    'tempinbox.com',
    'mohmal.com',
    'mintemail.com',
    'dispostable.com',
    'emailondeck.com',
    'spamgourmet.com',
    'mytemp.email',
    'temp-mail.io',
    'disposablemail.com',
    'spam4.me',
    'mailtemp.info',
    'tempsky.com',
    'emailna.co',
    'getairmail.com',
    'armyspy.com',
    'cuvox.de',
    'dayrep.com',
    'einrot.com',
    'fleckens.hu',
    'gustr.com',
    'jourrapide.com',
    'rhyta.com',
    'superrito.com',
    'teleworm.us',
    'inboxkitten.com',
    'tempmailo.com',
    'instantemailaddress.com',
    'mailcatch.com',
    'meltmail.com',
    'mailfree.ga',
    'tempmail.de',
    '0-mail.com',
    'bugmenot.com',
    'deadaddress.com',
    'dudmail.com',
    'emailsensei.com',
    'incognitomail.com',
    'jetable.org',
    'mailforspam.com',
    'mailfreeonline.com',
    'mailmoat.com',
    'mailscrap.com',
    'nospamfor.us',
    'spambox.us',
    'spamfree24.org',
    'spamstack.net',
    'trashmail.ws',
    'wegwerfmail.de',
    'wegwerfemail.de',
    'zehnminuten.de',
    'zehnminutenmail.de',
    '33mail.com',
    'anonbox.net',
    'binkmail.com',
    'bobmail.info',
    'boun.cr',
    'breakthru.com',
    'courriel.fr.nf',
    'discardmail.com',
    'dumpmail.de',
    'e4ward.com',
    'filzmail.com',
    'gishpuppy.com',
    'grr.la',
    'guerrillamailblock.com',
    'hatespam.org',
    'hidemail.de',
    'ihateyoualot.info',
    'imails.info',
    'ipoo.org',
    'irish2me.com',
    'jetable.fr.nf',
    'kasmail.com',
    'koszmail.pl',
    'lags.us',
    'letthemeatspam.com',
    'lhsdv.com',
    'lopl.co.cc',
    'lr78.com',
    'maboard.com',
    'mailbidon.com',
    'mailblocks.com',
    'mailexpire.com',
    'mailin8r.com',
    'mailme.ir',
    'mailme.lv',
    'mailnull.com',
    'mailshell.com',
    'mailzilla.com',
    'mbx.cc',
    'messagebeamer.de',
    'minmail.com',
    'mt2009.com',
    'mx0.wwwnew.eu',
    'mycleaninbox.net',
    'mypartyclip.de',
    'myphantomemail.com',
    'mytrashmail.com',
    'nervmich.net',
    'nervtmich.net',
    'netmails.com',
    'netmails.net',
    'netzidiot.de',
    'nobulk.com',
    'noclickemail.com',
    'nogmailspam.info',
    'nomail.xl.cx',
    'nomail2me.com',
    'nospam.ze.tc',
    'nospam4.us',
    'nowmymail.com',
    'objectmail.com',
    'obobbo.com',
    'oneoffemail.com',
    'onewaymail.com',
    'opayq.com',
    'ordinaryamerican.net',
    'owlpic.com',
    'pdabest.com',
    'pjjkp.com',
    'politikerclub.de',
    'poofy.org',
    'pookmail.com',
    'privacy.net',
    'privatdemail.net',
    'proxymail.eu',
    'prtnx.com',
    'putthisinyourspamdatabase.com',
    'quickinbox.com',
    'rcpt.at',
    'reallymymail.com',
    'realtyalerts.ca',
    'recode.me',
    'recursor.net',
    'regbypass.com',
    'rejectmail.com',
    'rmqkr.net',
    'rtrtr.com',
    's0ny.net',
    'safe-mail.net',
    'safersignup.de',
    'safetymail.info',
    'sandelf.de',
    'saynotospams.com',
    'schafmail.de',
    'sendspamhere.com',
    'shiftmail.com',
    'shitmail.me',
    'shortmail.net',
    'sibmail.com',
    'skeefmail.com',
    'slaskpost.se',
    'slopsbox.com',
    'smashmail.de',
    'smellfear.com',
    'snakemail.com',
    'sneakemail.com',
    'sofimail.com',
    'solvemail.info',
    'sogetthis.com',
    'soodonims.com',
    'spam.la',
    'spamavert.com',
    'spambob.com',
    'spambob.net',
    'spambob.org',
    'spambog.com',
    'spambog.de',
    'spambog.ru',
    'spambox.info',
    'spambox.irishspringrealty.com',
    'spamcannon.com',
    'spamcannon.net',
    'spamcero.com',
    'spamcon.org',
    'spamcorptastic.com',
    'spamcowboy.com',
    'spamcowboy.net',
    'spamcowboy.org',
    'spamday.com',
    'spamex.com',
    'spamfree.eu',
    'spamfree24.com',
    'spamfree24.de',
    'spamfree24.eu',
    'spamfree24.info',
    'spamfree24.net',
    'spamfree24.org',
    'spamgoes.in',
    'spamgourmet.net',
    'spamgourmet.org',
    'spamherelots.com',
    'spamhereplease.com',
    'spamhole.com',
    'spamify.com',
    'spaminator.de',
    'spamkill.info',
    'spaml.com',
    'spaml.de',
    'spammotel.com',
    'spamobox.com',
    'spamoff.de',
    'spamslicer.com',
    'spamspot.com',
    'spamthis.co.uk',
    'spamthisplease.com',
    'spamtrail.com',
    'speed.1s.fr',
    'supergreatmail.com',
    'supermailer.jp',
    'suremail.info',
    'teewars.org',
    'tempalias.com',
    'tempe-mail.com',
    'tempemail.biz',
    'tempemail.com',
    'tempemail.net',
    'tempinbox.co.uk',
    'tempinbox.com',
    'tempmail.eu',
    'tempmailer.com',
    'tempmailer.de',
    'tempomail.fr',
    'temporarily.de',
    'temporarioemail.com.br',
    'temporaryemail.net',
    'temporaryforwarding.com',
    'temporaryinbox.com',
    'thanksnospam.info',
    'thankyou2010.com',
    'thc.st',
    'thelimestones.com',
    'thisisnotmyrealemail.com',
    'throwawayemailaddress.com',
    'tilien.com',
    'tmailinator.com',
    'toiea.com',
    'tradermail.info',
    'trbvm.com',
    'trillianpro.com',
    'turual.com',
    'twinmail.de',
    'tyldd.com',
    'uggsrock.com',
    'upliftnow.com',
    'uplipht.com',
    'venompen.com',
    'veryrealemail.com',
    'viditag.com',
    'viewcastmedia.com',
    'viewcastmedia.net',
    'viewcastmedia.org',
    'webm4il.info',
    'wegwerfadresse.de',
    'wetrainbayarea.com',
    'wetrainbayarea.org',
    'wh4f.org',
    'whyspam.me',
    'willselfdestruct.com',
    'winemaven.info',
    'wronghead.com',
    'wuzup.net',
    'wuzupmail.net',
    'wwwnew.eu',
    'x.ip6.li',
    'xagloo.com',
    'xemaps.com',
    'xents.com',
    'xoxy.net',
    'yep.it',
    'yogamaven.com',
    'yopmail.fr',
    'yopmail.net',
    'ypmail.webarnak.fr.eu.org',
    'yuurok.com',
    'zippymail.info',
    'zoaxe.com',
    'zoemail.org'
]);

/**
 * Verifica se um domínio de email é temporário/descartável
 */
function isDisposableDomain(domain) {
    if (!domain || typeof domain !== 'string') {
        return false;
    }
    
    return DISPOSABLE_EMAIL_DOMAINS.has(domain.toLowerCase());
}

/**
 * Verifica se um email completo usa domínio temporário
 */
function isDisposableEmail(email) {
    if (!email || typeof email !== 'string') {
        return false;
    }
    
    const parts = email.toLowerCase().split('@');
    if (parts.length !== 2) {
        return false;
    }
    
    return isDisposableDomain(parts[1]);
}

/**
 * Adiciona novos domínios à blocklist
 */
function addDisposableDomains(domains) {
    if (!Array.isArray(domains)) {
        return;
    }
    
    domains.forEach(domain => {
        if (domain && typeof domain === 'string') {
            DISPOSABLE_EMAIL_DOMAINS.add(domain.toLowerCase());
        }
    });
}

/**
 * Retorna total de domínios bloqueados
 */
function getBlockedDomainsCount() {
    return DISPOSABLE_EMAIL_DOMAINS.size;
}

module.exports = {
    DISPOSABLE_EMAIL_DOMAINS,
    isDisposableDomain,
    isDisposableEmail,
    addDisposableDomains,
    getBlockedDomainsCount
};

