import {
  Home,
  UtensilsCrossed,
  Car,
  Banknote,
  Gamepad2,
  ShoppingBag,
  Heart,
  BookOpen,
  Plane,
  Zap,
  Music,
  Dumbbell,
  Briefcase,
  Smartphone,
  Package,
  Plus,
  Search,
  X,
  Trash2,
  Edit,
  Calendar,
  TrendingUp,
  TrendingDown,
  PieChart,
  BarChart3,
  Settings,
  User,
  Bell,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Info,
  RotateCcw,
  MessageCircle,
  Play,
  Pause,
  Upload,
  Download,
  Filter,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Star,
  StarOff,
  ThumbsUp,
  ThumbsDown,
  Share2,
  Copy,
  ExternalLink,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Menu,
  MoreHorizontal,
  MoreVertical,
  Grid,
  List,
  Map,
  Calendar as CalendarIcon,
  Clock,
  Timer,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Wifi,
  WifiOff,
  Battery,
  BatteryLow,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Camera,
  Image,
  Video,
  File,
  FileText,
  Folder,
  FolderOpen,
  Save,
  Archive,
  Bookmark,
  Tag,
  Flag,
  Pin,
  Paperclip,
  Link2,
  Send,
  Mail,
  Phone,
  MessageSquare,
  Users,
  UserPlus,
  UserMinus,
  Shield,
  ShieldCheck,
  Key,
  CreditCard,
  Wallet,
  Receipt,
  Calculator,
  Globe,
  MapPin,
  Navigation,
  Compass,
  Target,
  Crosshair,
  Maximize2,
  Minimize2,
  ZoomIn,
  ZoomOut,
  RefreshCcw,
  Power,
  LogOut,
  LogIn,
  Lightbulb,
} from 'lucide-react';

export const iconMap = {
  Home,
  UtensilsCrossed,
  Car,
  Banknote,
  DollarSign: Banknote,
  Gamepad2,
  ShoppingBag,
  Heart,
  BookOpen,
  Plane,
  Zap,
  Music,
  Dumbbell,
  Briefcase,
  Smartphone,
  Package,
  Plus,
  Search,
  X,
  Trash2,
  Edit,
  Calendar,
  Upload,
  Download,
  Filter,
  Copy,
  Share2,
  ExternalLink,
  Save,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Menu,
  MoreHorizontal,
  MoreVertical,
  TrendingUp,
  TrendingDown,
  PieChart,
  BarChart3,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Star,
  StarOff,
  ThumbsUp,
  ThumbsDown,
  CheckCircle,
  XCircle,
  AlertTriangle,
  Info,
  Bell,
  Settings,
  User,
  Users,
  UserPlus,
  UserMinus,
  Shield,
  ShieldCheck,
  Key,
  Power,
  LogOut,
  LogIn,
  Play,
  Pause,
  Camera,
  Image,
  Video,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  File,
  FileText,
  Folder,
  FolderOpen,
  Bookmark,
  Tag,
  Flag,
  Pin,
  Paperclip,
  Link2,
  Send,
  Mail,
  Phone,
  MessageSquare,
  MessageCircle,
  CreditCard,
  Wallet,
  Receipt,
  Calculator,
  Globe,
  MapPin,
  Navigation,
  Compass,
  Target,
  Crosshair,
  Map,
  Clock,
  Timer,
  CalendarIcon,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Wifi,
  WifiOff,
  Battery,
  BatteryLow,
  Grid,
  List,
  Maximize2,
  Minimize2,
  ZoomIn,
  ZoomOut,
  RotateCcw,
  RefreshCcw,
  Lightbulb,
};

export const categoryIconOptions = [
  { name: 'Home', icon: Home, label: 'Home' },
  { name: 'UtensilsCrossed', icon: UtensilsCrossed, label: 'Food & Dining' },
  { name: 'Car', icon: Car, label: 'Transportation' },
  { name: 'Banknote', icon: Banknote, label: 'Finance' },
  { name: 'Gamepad2', icon: Gamepad2, label: 'Entertainment' },
  { name: 'ShoppingBag', icon: ShoppingBag, label: 'Shopping' },
  { name: 'Heart', icon: Heart, label: 'Health & Wellness' },
  { name: 'BookOpen', icon: BookOpen, label: 'Education' },
  { name: 'Plane', icon: Plane, label: 'Travel' },
  { name: 'Zap', icon: Zap, label: 'Utilities' },
  { name: 'Music', icon: Music, label: 'Music & Audio' },
  { name: 'Dumbbell', icon: Dumbbell, label: 'Fitness' },
  { name: 'Briefcase', icon: Briefcase, label: 'Business & Work' },
  { name: 'Smartphone', icon: Smartphone, label: 'Technology' },
  { name: 'Package', icon: Package, label: 'General' },
];

export const getIcon = (iconName, fallback = 'Package') => {
  return iconMap[iconName] || iconMap[fallback] || Package;
};

export const hasIcon = (iconName) => iconName in iconMap;

export const getAvailableIconNames = () => Object.keys(iconMap);

